#!/usr/bin/env bash
# Auto-generated by launch_annealing_r1_qwen3.5_9b.sh (20260526_002937)
# DAPO on the annealing-R1 merged 9B model
export PATH=/dpc/kuin0100/conda_env/qwen35/bin:$PATH
export INIT_MODEL=/dpc/kuin0100/bohao/202509_InferenceModel/outputs/model_FT_merged/Qwen3.5-9B-TelecomInstruct_v2.6_try_v0_annealing_r1_qlora_stage3_checkpoint-34
export STAGE_NAME=stage2.0_grpo_eval
export EXPERIMENT_NAME=dapo_mixed_v3_stage2_0_grpoeval_qwen35_9b_annealing_r1
export MCQ_REWARD_MODE=v2
export TELEMATH_REWARD_MODE=v2
export MAX_CKPT=4
echo "[launcher] INIT_MODEL=$INIT_MODEL"
echo "[launcher] STAGE_NAME=$STAGE_NAME"
echo "[launcher] EXPERIMENT_NAME=$EXPERIMENT_NAME"
cd /dpc/kuin0100/bohao/202509_InferenceModel/Inference/verl
exec bash examples/grpo_TeleInfer/run_qwen3_5_27b_fsdp_mixed_v3_stage1_4_dapov2.sh
